set_property SRC_FILE_INFO {cfile:{C:/Users/Zach/Desktop/Work/School/Digital Electronics/VHDL/project_1/project_1.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc} rfile:../../../project_1.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {sw}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led}]
